version: "3.9"
services:
  db:
    image: postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    container_name: parking-app-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  parking-server-container:
    image: parking-server
    container_name: parking-app-server
    depends_on:
      - db
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command:
      - /bin/sh
      - -c
      - yarn knex migrate:latest && yarn dev